// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDvJ0spG0VZ7AfaWP0dCJF2Q_PR_4tZXk',
    appId: '1:757930163137:web:8f0a2cbb889b9101ff4d40',
    messagingSenderId: '757930163137',
    projectId: 'rent-app-majd',
    authDomain: 'rent-app-majd.firebaseapp.com',
    storageBucket: 'rent-app-majd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzzA5f8UQ7S7_NkslpdKp1-WCOrmTeVVs',
    appId: '1:757930163137:android:e2274f3c2099fd75ff4d40',
    messagingSenderId: '757930163137',
    projectId: 'rent-app-majd',
    storageBucket: 'rent-app-majd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXNmizxCUJ6aXVA5iEg1ZbQG4zgsMwr0U',
    appId: '1:757930163137:ios:5ca1e1481db5fab2ff4d40',
    messagingSenderId: '757930163137',
    projectId: 'rent-app-majd',
    storageBucket: 'rent-app-majd.firebasestorage.app',
    iosBundleId: 'com.example.rentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXNmizxCUJ6aXVA5iEg1ZbQG4zgsMwr0U',
    appId: '1:757930163137:ios:5ca1e1481db5fab2ff4d40',
    messagingSenderId: '757930163137',
    projectId: 'rent-app-majd',
    storageBucket: 'rent-app-majd.firebasestorage.app',
    iosBundleId: 'com.example.rentApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDvJ0spG0VZ7AfaWP0dCJF2Q_PR_4tZXk',
    appId: '1:757930163137:web:2035293d209d1390ff4d40',
    messagingSenderId: '757930163137',
    projectId: 'rent-app-majd',
    authDomain: 'rent-app-majd.firebaseapp.com',
    storageBucket: 'rent-app-majd.firebasestorage.app',
  );

}